version: '3'

services:
  php:
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/my-html
      - ./logs/apache2:/var/log/apache2
      - ./apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
    links:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: vicecity0
      MYSQL_ROOT_PASSWORD: vicecity0
      MYSQL_DATABASE: appDB
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql-init/:/docker-entrypoint-initdb.d/:ro

  front:
    image: nginx
    restart: always
    command: [ nginx, '-g', 'daemon off;' ]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/usr/share/nginx/my-html
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    links:
      - mysql
      - php

volumes:
  mysql: